#include<iostream>
using namespace std;
int main()
{
    char k[10001], b,ans;
    int n;
    cin>>n;
    for(int i=1; i<=n*n; i++)
    {
        cin>>k[i]>>b;
      if(k[i]=='K')
      {
          k[i]=13;
      }
      if(k[i]=='Q')
      {
          k[i]=13;
      }
      if(k[i]=='K')
      {
          k[i]=12;
      }if(k[i]=='J')
      {
          k[i]=11;
      }if(k[i]=='T')
      {
          k[i]=10;
      }if(k[i]=='9')
      {
          k[i]=9;
      }if(k[i]=='8')
      {
          k[i]=8;
      }if(k[i]=='7')
      {
          k[i]=7;
      }if(k[i]=='6')
      {
          k[i]=6;
      }if(k[i]=='5')
      {
          k[i]=5;
      }if(k[i]=='4')
      {
          k[i]=4;
      }if(k[i]=='3')
      {
          k[i]=3;
      }if(k[i]=='2')
      {
          k[i]=2;
      }
      if(k[i]=='A')
      {
          k[i]=1;
      }
    ans=k[n*3+1];
     if(k[i+1]>k[i+n])
     {
         ans=ans+k[i+1];
     }
     else{ans=ans+k[i+n];}
     if(k[i+n]>n*n)
     {
         break;
     }
    }
    cout<<ans;
    return 0;
}
