#include<iostream>
#include<cmath>
#include<algorithm>
using namespace std;
int n,a[128][128],maxs=0;
int s=0,st=0;
void read()
{
    char c1,c2;
    cin>>n;
    for(int i=0; i<n; i++)
    {
        for(int j=0; j<n; j++)
        {
            cin>>c1>>c2;
            if(c1=='A')
            {
                a[i][j]=1;
            }
            else
            {
                if(c1=='2')
                {
                    a[i][j]=2;
                }
                else
                {
                    if(c1=='3')
                    {
                        a[i][j]=3;
                    }
                    else
                    {
                        if(c1=='4')
                        {
                            a[i][j]=4;
                        }
                        else
                        {
                            if(c1=='5')
                            {
                                a[i][j]=5;
                            }
                            else
                            {
                                if(c1=='6')
                                {
                                    a[i][j]=6;
                                }
                                else
                                {
                                    if(c1=='7')
                                    {
                                        a[i][j]=7;
                                    }
                                    else
                                    {
                                        if(c1=='8')
                                        {
                                            a[i][j]=8;
                                        }
                                        else
                                        {
                                            if(c1=='9')
                                            {
                                                a[i][j]=9;
                                            }
                                            else
                                            {
                                                if(c1=='T')
                                                {
                                                    a[i][j]=10;
                                                }
                                                else
                                                {
                                                    if(c1=='J')
                                                    {
                                                        a[i][j]=11;
                                                    }
                                                    else
                                                    {
                                                        if(c1=='Q')
                                                        {
                                                            a[i][j]=12;
                                                        }
                                                        else
                                                        {
                                                            if(c1=='K')
                                                            {
                                                                a[i][j]=13;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
void DFS(int x, int y)
{
    st++;
    s+=a[x][y];
    if(x>0)
    {
        DFS(x-1,y);
        s-=a[x-1][y];
    }
    if(y<(n-1))
    {
        DFS(x,y+1);
        s-=a[x][y+1];
    }
    if(x==0 && y==(n-1))
    {
        if(s>maxs && (st-2)==((2*n)-2)) maxs=s;
    }
    st--;
}
int main()
{
    read();
    DFS(n,0);
    cout<<maxs<<endl;
    return 0;
}
