#include <iostream>
#include <string>
#include <queue>
using namespace std;

struct Tel {
	int st, br;
};
Tel a[111][111], p;
int n, i, j, tek;
string s;

int main () {
	cin >> n;
	for (i = 1; i <= n; i ++) {
		for (j = 1; j <= n; j ++) {
//			scanf ("%s", &s);
			cin >> s;
			cin.ignore();
			a[i][j].st = 1;
			if (s[0] >= '2' && s[0] <= '9') {
				a[i][j].st = s[0] - '0';
			}
			else {
				if (s[0] == 'A' ) a[i][j].st = 1;
				if (s[0] == 'T' ) a[i][j].st = 10;
				if (s[0] == 'J' ) a[i][j].st = 11;
				if (s[0] == 'Q' ) a[i][j].st = 12;
				if (s[0] == 'K' ) a[i][j].st = 13;
			}
		}
	}
	for (i = 1; i <= n; i ++) {
		a[n][i].br = a[n][i-1].br + a[n][i].st;
		a[n-i+1][1].br = a[n-i+2][1].br + a[n-i+1][1].st;
	}
//	cout << endl;
	for (i = n-1; i >= 1; i --) {
		for (j = 2; j <= n; j ++) {
			a[i][j].br = max(a[i][j-1].br, a[i+1][j].br) + a[i][j].st;
		}
	}
//	for (i = 1; i <= n; i ++) {
//		for (j = 1; j <= n; j ++) {
//			cout << a[i][j].br << " ";
//		}
//		cout << endl;
//	}
	cout << a[1][n].br << endl;
	return 0;
}
/*
4
8S AD 3C AC
8C 4H QD QS
5D 9H KC 7H
TC QC AS 2D


5
4S 6C 7D 8H 9S
3D 5C 6H 5C 8C
2C 2S 4H 6D 7H
2C 3H 2D 5D 6D
AS 2C 2B 3H 4C


100
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS AH AC AD AS
*/
