#include<iostream>
using namespace std;
int main()
{
    int day=0,brvak=0,a;
    char d[3],m[3],y[5];
    int first_day;
    cin.getline(d,3,'/');
    cin.getline(m,3,'/');
    cin>>y>>a;
    if(d[1]==0)
    {
        day+=(d[0]-'0');
    }
    if(d[1]!=0)
    {
        day=day+(d[0]-'0')*10+(d[1]-'0');
    }
    if(y[3]=='9')
    {
        if(m[1]==0)
        {
            if(m[0]=='1')
            {
                first_day=(2+day%7)%7;
            }
            if(m[0]=='2')
            {
                first_day=(5+day%7)%7;

            }
            if(m[0]=='3')
            {
                first_day=(5+day%7)%7;
            }
            if(m[0]=='4')
            {
                first_day=(1+day%7)%7;
            }
            if(m[0]=='5')
            {
                first_day=(3+day%7)%7;
            }
            if(m[0]=='6')
            {
                first_day=(6+day%7)%7;
            }
            if(m[0]=='7')
            {
                first_day=(1+day%7)%7;
            }
            if(m[0]=='8')
            {
                first_day=(4+day%7)%7;
            }
            if(m[0]=='9')
            {
                first_day=(7+day%7)%7;
            }
        }
        else
        {
            if(m[1]='0')
            {
                first_day=(2+day%7)%7;
            }
            if(m[1]='1')
            {
                first_day=(5+day%7)%7;
            }
            if(m[1]='2')
            {
                first_day=(7+day%7)%7;
            }
        }
    }
    else
    {
        if(m[1]==0)
        {
            if(m[0]=='1')
            {
                first_day=(3+day%7)%7;
            }
            if(m[0]=='2')
            {
                first_day=(6+day%7)%7;

            }
            if(m[0]=='3')
            {
                first_day=(7+day%7)%7;
            }
            if(m[0]=='4')
            {
                first_day=(3+day%7)%7;
            }
            if(m[0]=='5')
            {
                first_day=(5+day%7)%7;
            }
            if(m[0]=='6')
            {
                first_day=(1+day%7)%7;
            }
            if(m[0]=='7')
            {
                first_day=(3+day%7)%7;
            }
            if(m[0]=='8')
            {
                first_day=(6+day%7)%7;
            }
            if(m[0]=='9')
            {
                first_day=(2+day%7)%7;
            }
        }
        else
        {
            if(m[1]='0')
            {
                first_day=(4+day%7)%7;
            }
            if(m[1]='1')
            {
                first_day=(7+day%7)%7;
            }
            if(m[1]='2')
            {
                first_day=(2+day%7)%7;
            }
        }
    }
    int pochivni_dni=0;
    while(pochivni_dni<a)
    {
        if(first_day>0 and first_day<6)
        {
            pochivni_dni++;
        }
        brvak++;
        first_day++;
        first_day=first_day%7;
    }
    for(int i=0; i<brvak;i++, day++)
    {
        if(day==32 and m[0]=='1' and m[1]=='2')
        {
            m[0]='1';
            m[1]=0;
            day=1;
            if(y[3]==9)
            {
                y[2]='2';
                y[3]='0';
            }
            else{
                y[3]++;
            }
        }
        if(day==32)
        {
            if(m[1]==0)
            {
                m[0]++;
            }
            else
            {
                m[1]++;
            }
            day=1;
        }
        if(day==31)
        {
            if(m[1]==0)
            {
                if(m[0]=='4' or m[0]=='6')
                {
                    m[0]++;
                    day=1;
                }
                if(m[0]=='9')
                {
                    m[0]='1';
                    m[1]='0';
                    day=1;
                }
            }
            else if(m[1]=='1')
            {
                m[1]++;
                day=1;
            }
        }
        if(day==30 and m[0]=='2' and y[3]=='0')
        {
            day=1;
            m[0]='3';
        }
        if(day==29 and m[0]=='2' and y[3]=='9')
        {
            day=1;
            m[0]='3';
        }
    }
    if(day/10==0)
    {
        cout<<0<<day<<".";
    }
    else
    {
        cout<<day<<".";
    }
    if(m[1]==0)
    {
        cout<<'0'<<m<<".";
    }
    else
    {
        cout<<m<<".";
    }
    cout<<y<<endl;
    return 0;
}
