#include<iostream>
using namespace std;
int main()
{
    long long x,n;
    cin>>n>>x;
    n%=6;
    if(n==0&&x==0)
    {
        cout<<0<<endl;
    }
    if(n==0&&x==1)
    {
        cout<<1<<endl;
    }
    if(n==0&&x==2)
    {
        cout<<2<<endl;
    }
    if(n==1&&x==0)
    {
        cout<<1<<endl;
    }
    if(n==1&&x==1)
    {
        cout<<0<<endl;
    }
    if(n==1&&x==2)
    {
        cout<<2<<endl;
    }
    if(n==2&&x==0)
    {
        cout<<2<<endl;
    }
    if(n==2&&x==1)
    {
        cout<<0<<endl;
    }
    if(n==2&&x==2)
    {
        cout<<1<<endl;
    }
    if(n==3&&x==0)
    {
        cout<<2<<endl;
    }
    if(n==3&&x==1)
    {
        cout<<1<<endl;
    }
    if(n==3&&x==2)
    {
        cout<<0<<endl;
    }
    if(n==4&&x==0)
    {
        cout<<1<<endl;
    }
    if(n==4&&x==1)
    {
        cout<<2<<endl;
    }
    if(n==4&&x==2)
    {
        cout<<0<<endl;
    }
    if(n==5&&x==0)
    {
        cout<<0<<endl;
    }
    if(n==5&&x==1)
    {
        cout<<2<<endl;
    }
    if(n==5&&x==2)
    {
        cout<<1<<endl;
    }
    return 0;
}
