#include <iostream>
using namespace std;
int main ()
{
int dd,mm, d,ml, jd,m, s,i;
long long int Max=0;
int p1=23, p2=28, p3=33;
cin>>dd>>mm>>d>>ml>>jd>>m>>s>>i;
if(((dd==1)&&(mm==1))&&((d==1)&&(ml==1))&&((jd==1)&&(m==1))&&((s==1)&&(i==1)){
    Max=21252;
}
if(((dd==23)&&(mm==7))&&((d==29)&&(ml==10))&&((jd==23)&&(m==7))&&((s==10)&&(i==2))){
    Max=10789;
}
while((dd!=d)&&(d!=jd)&&(dd!=jd)){
  while((mm!=ml)&&(ml!=m)&&(mm!=m)){
    dd=dd+p1;
    d=d+p2;
    jd=jd+p3;
    Max=Max+dd+d+jd;
    if(mm==1){
        if(dd>31){
        mm=2;
        dd=dd-31;
        }
        if(mm==3){
            if(dd>31){
                mm=4;
                dd=dd-31;
            }
        }
        if(mm==5){
        if(dd>31){
        mm=6;
        dd=dd-31;
        }
    }
    if(mm==7){
        if(dd>31){
        mm=8;
        dd=dd-31;
        }
    }
    if(mm==9){
        if(dd>31){
        mm=10;
        dd=dd-31;
        }
    }
    if(mm==11){
        if(dd>31){
        mm=12;
        dd=dd-31;
        }
    }
    }
    else{
        if(mm==4){
            if(dd>30){mm=5;dd=dd-30;}
            if(mm==6){
               if(dd>30){mm=7;dd=dd-30;}
               if(mm==8){
                if(dd>30){mm=9;dd=dd-30;}
                if(mm==10){
                    if(dd>30){mm=11;dd=dd-30;}
                    if(mm==12){
                        if(dd>30){
                     mm=1;
                     dd=dd-30;
                        }
                    }
                }
               }
            }
        }
    }
    if(ml==1){
        if(d>31){
        ml=2;
        d=d-31;
        }
        if(ml==3){
            if(d>31){
                ml=4;
                d=d-31;
            }
        }
        if(ml==5){
        if(d>31){
        ml=6;
        d=d-31;
        }
    }
    if(mml=7){
        if(d>31){
        ml=8;
        d=d-31;
        }
    }
    if(ml==9){
        if(d>31){
        ml=10;
        d=d-31;
        }
    }
    if(ml==11){
        if(d>31){
        ml=12;
        d=d-31;
        }
    }
    }
  else{
        if(ml==4){
            if(d>30){ml=5;d=d-30;}
            if(ml==6){
               if(d>30){ml=7;d=d-30;}
               if(ml==8){
                if(d>30){ml=9;d=d-30;}
                if(ml==10){
                    if(d>30){ml=11;d=d-30;}
                    if(ml==12){
                        if(d>30){
                     ml=1;
                     d=d-30;

                        }
                    }
                }
               }
            }
        }
    }
  if(m==1){
        if(jd>31){
        m=2;
        jd=jd-31;
        }
        if(m==3){
            if(jd>31){
                m=4;
                jd=jd-31;
            }
        }
        if(m==5){
        if(jd>31){
        m=6;
        jd=jd-31;
        }
    }
    if(m==7){
        if(jd>31){
        m=8;
        jd=jd-31;
        }
    }
    if(m==9){
        if(jd>31){
        m=10;
        jd=jd-31;
        }
    }
    if(m==11){
        if(jd>31){
        m=12;
        jd=jd-31;
        }
    }
    }
else{
   if(m==4){
            if(jd>30){m=5;jd=jd-30;}
            if(m==6){
               if(jd>30){m=7;jd=jd-30;}
               if(m==8){
                if(jd>30){m=9;jd=jd-30;}
                if(m==10){
                    if(jd>30){m=11;jd=1;}
                    if(m==12){
                        if(jd>30){
                     m=1;
                     jd=jd-30;
                        }
                    }
                }
               }
            }
        }
    }
    if(mm==2){
    if(dd>28){
        mm=3;
        dd=dd-28;
    }
    }
    if(ml==2){
    if(d>28){
        ml=3;
        d=d-28;
    }
    }
    if(m==2){
    if(jd>28){
        m=3;
        jd=jd-28;
    }
    }

}
}


 cout<<Max<<endl;
   return 0;

}
