#include<iostream>
using namespace std;
int main()
{
    int n,k,br=0;
    cin>>n>>k;
    while(n!=0)
    {
        n=n/10;
        br++;
    }
    if(br==1)
    {
        br=1;
        cout<<2*k;
    }
    else
    {
        if(br==2)
        {
            br=10;
            cout<<3*k;
        }
        else
        {
            if(br==3)
            {
                br=100;
                cout<<4*k;
            }
            else
            {
                if(br==4)
                {
                    br=1000;
                    cout<<5*k;
                }
                else
                {
                    if(br==5)
                    {
                        br=10000;
                        cout<<6*k;
                    }
                    else
                    {
                        if(br==6)
                        {
                            br=100000;
                            cout<<7*k;
                        }
                        else
                        {

                        }    if(br==7)
                        {
                            br=1000000;
                            cout<<8*k;
                        }
                        else
                        {
                            if(br==8)
                            {
                                br=10000000;
                                cout<<9*k;
                            }
                            else
                            {
                                if(br==9)
                                {
                                    br=100000000;
                                    cout<<10*k;
                                }
                                else
                                {
                                    if(br==10)
                                    {
                                        br=1000000000;
                                        cout<<11*k;
                                    }
                                    else
                                    {
                                        if(br==11)
                                        {
                                            br=10000000000;
                                            cout<<12*k;
                                        }
                                        else
                                        {
                                            if(br==12)
                                            {
                                                br=100000000000;
                                                cout<<13*k;
                                            }
                                            else
                                            {
                                                if(br==13)
                                                {
                                                    br=1000000000000;
                                                    cout<<14*k;
                                                }
                                                else
                                                {
                                                    if(br==14)
                                                    {
                                                        br=10000000000000;
                                                        cout<<15*k;
                                                    }
                                                    else
                                                    {
                                                        if(br==15)
                                                        {
                                                            br=100000000000000;
                                                            cout<<16*k;
                                                        }
                                                        else
                                                        {

                                                        }    if(br==16)
                                                        {
                                                            br=1000000000000000;
                                                            cout<<17*k;
                                                        }
                                                        else
                                                        {
                                                            if(br==17)
                                                            {
                                                                br=10000000000000000;
                                                                cout<<18*k;
                                                            }
                                                            else
                                                            {
                                                                if(br==18)
                                                                {
                                                                    br=100000000000000000;
                                                                    cout<<19*k;
                                                                }
                                                                else
                                                                {
                                                                    cout<<"NO";
                                                                }
                                                            }
                                                        }
}}            }                                        }}}}}}}}}}}                                    }}
