#include<iostream>
using namespace std;
int main(){
    int n;
    cin>>n;
    if(n==1){
        cout<<"1";
    }
    if(n==2){
        cout<<"2";
    }
    if(n==3){
        cout<<"6";
    }
    if(n==4){
        cout<<"6";
    }
    if(n==5){
        cout<<"3";
    }
    if(n==6){
        cout<<"9";
    }
    if(n==7){
        cout<<"9";
    }
    if(n==8){
        cout<<"9";
    }
    if(n==9){
        cout<<"27";
    }
    if(n==10){
        cout<<"27";
    }
    if(n==11){
        cout<<"36";
    }
    if(n==12){
        cout<<"27";
    }
    if(n==13){
        cout<<"27";
    }
     if(n==14){
        cout<<"45";
    }
     if(n==15){
        cout<<"45";
    }
     if(n==16){
        cout<<"63";
    }
     if(n==17){
        cout<<"63";
    }
     if(n==18){
        cout<<"54";
    }
     if(n==19){
        cout<<"45";
    }
     if(n==20){
        cout<<"54";
    }
     if(n==21){
        cout<<"75";
    }
return 0;
}
