#include<iostream>
using namespace std;
int main(){
long long ProbvanoChislo,KolkoCifrenoDaE,NaKakvoDaSeDeli;
bool NamerihLiChislo=false;
cin>>KolkoCifrenoDaE>>NaKakvoDaSeDeli;
if(KolkoCifrenoDaE==1){
    for(ProbvanoChislo=1;ProbvanoChislo<10;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==2){
    for(ProbvanoChislo=10;ProbvanoChislo<99;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==3){
    for(ProbvanoChislo=100;ProbvanoChislo<999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==4){
    for(ProbvanoChislo=1000;ProbvanoChislo<9999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==5){
    for(ProbvanoChislo=10000;ProbvanoChislo<99999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==6){
    for(ProbvanoChislo=100000;ProbvanoChislo<999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==7){
    for(ProbvanoChislo=1000000;ProbvanoChislo<9999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==8){
    for(ProbvanoChislo=10000000;ProbvanoChislo<99999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==9){
    for(ProbvanoChislo=100000000;ProbvanoChislo<999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==10){
    for(ProbvanoChislo=1000000000;ProbvanoChislo<9999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==11){
    for(ProbvanoChislo=10000000000;ProbvanoChislo<99999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==12){
    for(ProbvanoChislo=100000000000;ProbvanoChislo<999999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==13){
    for(ProbvanoChislo=1000000000000;ProbvanoChislo<9999999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==14){
    for(ProbvanoChislo=10000000000000;ProbvanoChislo<99999999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==15){
    for(ProbvanoChislo=100000000000000;ProbvanoChislo<999999999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==16){
    for(ProbvanoChislo=1000000000000000;ProbvanoChislo<9999999999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==17){
    for(ProbvanoChislo=10000000000000000;ProbvanoChislo<99999999999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(KolkoCifrenoDaE==18){
    for(ProbvanoChislo=100000000000000000;ProbvanoChislo<999999999999999999;ProbvanoChislo=ProbvanoChislo+1){
        if(ProbvanoChislo%NaKakvoDaSeDeli==0){
            NamerihLiChislo=true;
            cout<<ProbvanoChislo;
            break;
        }
    }
}
if(!NamerihLiChislo){
    cout<<"NO";
}
return 0;
}
