#include<iostream>
using namespace std;
int main()
{
 long long n;
 long long x;
 long long ch1=0,ch2=0,ch3=0,minava=1;
 cin>>n>>x;
 if(x==0){
    ch1=1;
     for(int i=1;i<n;i++){
    if(i%2==1){
       if(minava%3==1){
        ch2=ch1;
        ch1=0;
       }else{
       if(minava%3==0){
        ch3=ch2;
        ch2=0;
       }else{
       if(minava%3==2){
        ch1=ch3;
        ch3=0;
       }
       }
    }
       if(i%2==0){
        if(minava%3==2){
            ch3=ch1;
            ch1=0;
        }else{
        if(minava%3==1){
            ch1=ch2;
            ch2=0;
        }else{
        if(minava%3==0){
            ch2=ch3;
            ch3=0;
        }
        }
        }
       }
    }
 }
 }
  if(x==1){
    ch2=1;
     for(int i=1;i<n;i++){
    if(i%2==1){
       if(minava%3==1){
        ch2=ch1;
        ch1=0;
       }else{
       if(minava%3==0){
        ch2=ch3;
        ch3=0;
       }else{
       if(minava%3==2){
        ch3=ch2;
        ch2=0;
       }
       }
    }
       if(i%2==0){
        if(minava%3==2){
            ch3=ch1;
            ch1=0;
        }else{
        if(minava%3==1){
            ch1=ch2;
            ch2=0;
        }else{
        if(minava%3==0){
            ch1=ch2;
            ch2=0;
        }
        }
        }
       }
    }
 }
  }
  if(x==2){
    ch3=1;
     for(int i=1;i<n;i++){
    if(i%2==1){
       if(minava%3==1){
        ch2=ch1;
        ch1=0;
       }else{
       if(minava%3==0){
        ch3=ch2;
        ch2=0;
       }else{
       if(minava%3==2){
        ch2=ch3;
        ch3=0;
       }
       }
    }
       if(i%2==0){
        if(minava%3==2){
            ch1=ch3;
            ch3=0;
        }else{
        if(minava%3==1){
            ch2=ch1;
            ch1=0;
        }else{
        if(minava%3==0){
            ch3=ch1;
            ch1=0;
        }
        }
        }
       }
    }
 }
  }
 if(ch2==1){
    cout<<0;
 }else{
 if(ch3==1){
 cout<<1;
 }else{
 if(ch1==1){
    cout<<2;;
 }
 }
 }
return 0;

  }
