#include <iostream>
using namespace std;
int main(){

long long L,N;
cin>>N>>L;
long long index,izgubeniCifri[L],naiGoliamNomer=0;
for(index=0;index<L;index=index+1){
    cin>>izgubeniCifri[index];
}
long long a[N],b[N],c[N],d[N],e[N],f[N],g[N],nomera[N];
for(index=0;index<N;index=index+1){
    nomera[index]=index+1;
}
for(index=0;index<N;index=index+1){
    while(nomera[index]==nomera[index-1]){
        nomera[index]=nomera[index]+1;
    }
    a[index]=nomera[index]/1000000;
    b[index]=(nomera[index]-a[index]*1000000)/100000;
    c[index]=(nomera[index]-a[index]*1000000-b[index]*100000)/10000;
    d[index]=(nomera[index]-a[index]*1000000-b[index]*100000-c[index]*10000)/1000;
    e[index]=(nomera[index]-a[index]*1000000-b[index]*100000-c[index]*10000-d[index]*1000)/100;
    f[index]=(nomera[index]-a[index]*1000000-b[index]*100000-c[index]*10000-d[index]*1000-e[index]*100)/10;
    g[index]=nomera[index]%10;
    if(a[index]<=0&&b[index]<=0){
        a[index]=0;
        b[index]=0;
        if(L==3){
            for(;c[index]!=izgubeniCifri[1,2,0] && d[index]!=izgubeniCifri[1,2,0] && e[index]!=izgubeniCifri[1,2,0] && f[index]!=izgubeniCifri[1,2,0] && g[index]!=izgubeniCifri[0,1,2];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==2){
            for(;c[index]!=izgubeniCifri[0,1]&&d[index]!=izgubeniCifri[0,1]&&e[index]!=izgubeniCifri[0,1]&&f[index]!=izgubeniCifri[0,1]&&g[index]!=izgubeniCifri[0,1];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==1){
            for(;c[index]!=izgubeniCifri[0]&&d[index]!=izgubeniCifri[0]&&e[index]!=izgubeniCifri[0]&&f[index]!=izgubeniCifri[0]&&g[index]!=izgubeniCifri[0];){
                nomera[index]=nomera[index]+1;
            }
        }
    }
    if(a[index]&&b[index]&&c[index]<=0){
        a[index]=0;
        b[index]=0;
        c[index]=0;
         if(L==3){
            for(;d[index]!=izgubeniCifri[1,2,0]&&e[index]!=izgubeniCifri[1,2,0]&&f[index]!=izgubeniCifri[1,2,0]&&g[index]!=izgubeniCifri[0,1,2];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==2){
            for(;d[index]!=izgubeniCifri[0,1]&&e[index]!=izgubeniCifri[0,1]&&f[index]!=izgubeniCifri[0,1]&&g[index]!=izgubeniCifri[0,1];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==1){
            for(;d[index]!=izgubeniCifri[0]&&e[index]!=izgubeniCifri[0]&&f[index]!=izgubeniCifri[0]&&g[index]!=izgubeniCifri[0];){
                nomera[index]=nomera[index]+1;
            }
        }
    }
    if(a[index]&&b[index]&&c[index]&&d[index]<=0){
        a[index]=0;
        b[index]=0;
        c[index]=0;
        d[index]=0;
         if(L==3){
            for(;e[index]!=izgubeniCifri[1,2,0]&&f[index]!=izgubeniCifri[1,2,0]&&g[index]!=izgubeniCifri[0,1,2];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==2){
            for (;e[index]!=izgubeniCifri[0,1]&&f[index]!=izgubeniCifri[0,1]&&g[index]!=izgubeniCifri[0,1];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==1){
            for(;e[index]!=izgubeniCifri[0]&&f[index]!=izgubeniCifri[0]&&g[index]!=izgubeniCifri[0];){
                nomera[index]=nomera[index]+1;
            }
        }
    }
    if(a[index]&&b[index]&&c[index]&&d[index]&&e[index]<0){
        a[index]=0;
        b[index]=0;
        c[index]=0;
        d[index]=0;
        e[index]=0;
         if(L==3){
            for(;f[index]!=izgubeniCifri[1,2,0]&&g[index]!=izgubeniCifri[0,1,2];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==2){
            for(;f[index]!=izgubeniCifri[0,1]&&g[index]!=izgubeniCifri[0,1];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==1){
            for(;f[index]!=izgubeniCifri[0]&&g[index]!=izgubeniCifri[0];){
                nomera[index]=nomera[index]+1;
            }
        }
    }
    if(a[index]&&b[index]&&c[index]&&d[index]&&e[index]&&f[index]<=0){
        a[index]=0;
        b[index]=0;
        c[index]=0;
        d[index]=0;
        e[index]=0;
        f[index]=0;
         if(L==3){
            for(;g[index]!=izgubeniCifri[0,1,2];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==2){
            for(;g[index]!=izgubeniCifri[0,1];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(L==1){
            for(;g[index]!=izgubeniCifri[0];){
                nomera[index]=nomera[index]+1;
            }
        }
        if(nomera[index]>naiGoliamNomer){
            naiGoliamNomer=nomera[index];
        }
    }
}
cout<<nomera[N-1];

return 0;
}
