#include <iostream>

using namespace std;

int main () {

		return 0;
}
//TUK PYK SYVSEM NE RAZBIRAM ZADACHATA//
//KAK OT 1/1 1/1 1/1 1/1 SE POLUCHAVA 21252//
//KATO SE IMA PREDVID CHE PROCHETOH USLOVIEO BUKVALNO 15 PYTI//
//TAKA CHE NE MI IZLIZAJTE S IZVINENIETO DA SI PROCHETA USLOVIETO//
